nb_simu: 100        # Nb. of simulations
sample_size: 30    # Sample size
lambda_x: .9        # Parameter of exponential distribution for X
lambda_z: 1         # Parameter of exponential distribution for Z
alpha_y: 5          # Parameter of Pareto distribution for Y
out_file: 'simulation_output.txt'