nb_simu: 10000        # Nb. of simulations
sample_size: [100, 200, 500, 1000]    # Sample size, can be an array of multiple values
lambda_x: [.4, .5, .6, .7, .8]        # Parameter of exponential distribution for X
lambda_z: [1]         # Parameter of exponential distribution for Z
alpha_y: [2, 3, 4, 5, 8]          # Parameter of Pareto distribution for Y