nb_simu: 100                                              # Nb. of simulations
sample_size: [100, 200]                              # Sample size, can be an array of multiple values
lambda_x: [.05, .1]         # Parameter of exponential distribution for X
lambda_z: [1]                                              # Parameter of exponential distribution for Z
alpha_y: [20]   # Parameter of Pareto distribution for Y