nb_simu: 1000                                              # Nb. of simulations
sample_size: [100, 500, 1000]                              # Sample size, can be an array of multiple values
lambda_x: [.05, .1, .25, .4, .5, .6, .75, .9, .95]         # Parameter of exponential distribution for X
lambda_z: [1]                                              # Parameter of exponential distribution for Z
alpha_y: [20, 10, 4, 2.5, 2, 1.666, 1.333, 1.111, 1.053]   # Parameter of Pareto distribution for Y